language: node_js
node_js:
  - "7"

services:
  - mysql

before_install:
  - npm install -g codecov istanbul typescript

install:
  - npm install

before_script:
  - mysql -e 'CREATE SCHEMA pipelines;'
  - echo "# DB AUTH" >> .env
  - echo DB_DRIVER=mysql >> .env
  - echo DB_HOST=127.0.0.1 >> .env
  - echo DB_USER=root >> .env
  - echo DB_PASS= >> .env
  - echo DB_NAME=pipelines >> .env
  - npm run build

script:
  - npm run test

after_success:
  - ./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/coverage.json
  - istanbul report
  - codecov

deploy:
  provider: npm
  email: "admin@parpe.com"
  api_key: "307317b6-1f2b-4d67-9bf2-a820b6c8ee2d"
  on:
    branch: master