language: node_js
node_js:
  - "7"

services:
  - mysql

notifications:
  slack: parpe:ypxSy7CvUXYAShDK7C3supzV

before_install:
  - npm install -g codecov istanbul typescript

install:
  - npm install

before_script:
  - mysql -e 'CREATE SCHEMA pipelines;'
  - echo "# App information" >> .env
  - echo APP_SECRET = I4mY0urP455Phr4s3 >> .env
  - echo APP_INFO_ROUTE = /app/info >> .env
  - echo "# DB AUTH" >> .env
  - echo DB_DRIVER=mysql >> .env
  - echo DB_HOST=127.0.0.1 >> .env
  - echo DB_USER=root >> .env
  - echo DB_PASS= >> .env
  - echo DB_NAME=pipelines >> .env
  - echo SLACK_HOOK=$SLACK_HOOK_URL >> .env
  - npm run build

script:
  - npm run test

after_success:
  - codecov

deploy:
  provider: npm
  email: "admin@parpe.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master